/* The site's chrome: the nav bar and the OG strip on the home page, checked from the source. No server.
   The bar has one row to spend, so its text rides its own two tokens and the menu collapses into the pop-down
   whenever the row would not fit — measured by nav.js, not guessed by width. The OG banner is a strip whose
   head is always shown and whose rest pops down on a tap. */
import { readFileSync, readdirSync } from 'node:fs';
import path from 'node:path';
import { ROOT } from './_paths.mjs';

const PUB = path.join(ROOT, 'public');
const read = (f) => readFileSync(path.join(PUB, f), 'utf8');
const CSS = read('styles.css'), NAV = read('nav.js'), HOME = read('home.js'), INDEX = read('index.html');
const results = [];
const check = (n, ok, extra) => results.push([n, !!ok, extra === undefined ? '' : String(extra)]);

try {
  /* ═══ the bar ═══ */
  check('the nav\'s text rides its own scale: links and the wordmark on --nav-fs, the pills on --nav-fs-s, every control --nav-ctl tall', /\.nav-menu a \{[^}]*font-size: var\(--nav-fs\);[^}]*min-height: var\(--nav-ctl\);/.test(CSS) && /\.nav-logo span \{[^}]*calc\(var\(--nav-fs\) \* 1\.35\)/.test(CSS) && /\.nav-live-lbl \{[^}]*var\(--nav-fs-s\)/.test(CSS) && /\.profile-link \{[^}]*font-size: var\(--nav-fs\);/.test(CSS) && /\.notif-bell \{[^}]*width: var\(--nav-ctl\); height: var\(--nav-ctl\);/.test(CSS));
  check('  ...44px tall where a finger does the pointing', /@media \(pointer: coarse\) \{ :root \{ --nav-ctl: 44px; \} \}/.test(CSS));
  check('  ...and the bar never wraps its own children (one row: logo, menu or toggle, cluster)', /\.nav \{\n  position: sticky; top: 0; z-index: 50;\n  display: flex; align-items: center; gap: 0\.75rem; flex-wrap: nowrap; min-height: 60px;/.test(CSS));
  check('the pop-down form is a class nav.js sets, not a fixed breakpoint (the old 1280px media block is gone)', /\.nav\.is-compact \.nav-menu\.open \{/.test(CSS) && /\.nav\.is-compact \.nav-toggle \{/.test(CSS) && /\.nav\.is-compact \.nav-bal \{/.test(CSS) && !/@media \(max-width: 1280px\) \{[^}]*\.nav-menu/.test(CSS));
  check('  ...pop-down links are 44px tall and may wrap; row links never wrap', /\.nav\.is-compact \.nav-menu a \{[^}]*min-height: 44px;[^}]*white-space: normal;/.test(CSS) && /\.nav-menu a \{[^}]*white-space: nowrap;/.test(CSS));
  check('nav.js measures: a row that wraps (the search box counts) or overflows becomes compact; below 900px always', /menu\.getBoundingClientRect\(\)\.height > first\.getBoundingClientRect\(\)\.height \* 1\.5/.test(NAV) && /return !wrapped && !overflowing\(\);/.test(NAV) && /if \(window\.innerWidth >= 900\) \{/.test(NAV) && /nav\.classList\.add\('is-compact'\)/.test(NAV));
  check('  ...on a wide screen the inline row is tried again without the live count and the points before the bar collapses (links first)', /else \{ nav\.classList\.add\('is-tight'\); if \(rowFits\(\)\) compact = false; else nav\.classList\.remove\('is-tight'\); \}/.test(NAV));
  check('nothing in the row is ever squashed; a row that still does not fit steps down through measured tiers', /\.nav > \*:not\(\.nav-menu\), #nav-auth\.nav-persist > \*, \.nav-profile > \* \{ flex-shrink: 0; \}/.test(CSS) && /var TIERS = \['is-tight', 'is-tighter', 'is-tightest'\];/.test(NAV) && /if \(compact\) for \(var i = 0; i < TIERS\.length && overflowing\(\); i\+\+\) nav\.classList\.add\(TIERS\[i\]\);/.test(NAV) && /\.nav\.is-tight \.nav-live/.test(CSS) && /\.nav\.is-tighter \.nav-logo span, \.nav\.is-tighter \.profile-link \.pl-name \{ display: none; \}/.test(CSS) && /\.nav\.is-tightest \.nav-xp \{ display: none; \}/.test(CSS));
  check('  ...the @name is shown whole or not at all (never cut with "…"); no control in the bar is ever smaller than --nav-ctl (the 36px bell is gone)', /\.profile-link \.pl-name \{ display: inline-block; white-space: nowrap; vertical-align: bottom; \}/.test(CSS) && !/\.pl-name \{[^}]*text-overflow: ellipsis/.test(CSS) && !/\.notif-bell \{ width: 36px/.test(CSS) && /\.motion-btn \{[^}]*min-width: var\(--nav-ctl\); min-height: var\(--nav-ctl\);/.test(CSS));
  check('  ...the search is on the nav scale at a control\'s height; an icon in the inline row, a full field in the pop-down', /padding: 0 1rem 0 2\.1rem; height: var\(--nav-ctl\); box-sizing: border-box; font-size: var\(--nav-fs\);/.test(CSS) && /\.nav:not\(\.is-compact\) \.nav-search \{ position: relative; width: var\(--nav-ctl\);/.test(CSS) && !/@media \(min-width: 1281px\) and \(max-width: 1599px\)/.test(CSS));
  check('  ...and measures again on resize, on sign-in, when the cluster changes size, and once the fonts are in', /window\.addEventListener\('resize', fitSoon\)/.test(NAV) && /addEventListener\('auth:change'/.test(NAV) && /new ResizeObserver\(fitSoon\)\.observe\(cluster\)/.test(NAV) && /document\.fonts\.ready\.then\(fit, fit\)/.test(NAV) && !/matchMedia\('\(min-width: 1281px\)'\)/.test(NAV));
  check('  ...publishing the bar\'s real height when the form changes (sticky sub-bars read --nav-h)', /if \(compact !== wasCompact\) syncNavHeight\(\);/.test(NAV));
  const pages = readdirSync(PUB).filter((f) => f.endsWith('.html') && /<nav class="nav/.test(readFileSync(path.join(PUB, f), 'utf8')));
  const loose = pages.filter((f) => !/<nav class="nav is-compact" /.test(readFileSync(path.join(PUB, f), 'utf8')));
  check('  ...and measuring never flashes the closed menu: transitions are off while the classes flip', /nav\.classList\.add\('is-measuring'\)/.test(NAV) && /void menu\.offsetHeight;/.test(NAV) && /nav\.classList\.remove\('is-measuring'\)/.test(NAV) && /\.nav\.is-measuring \.nav-menu, \.nav\.is-measuring \.nav-menu \* \{ transition: none !important; \}/.test(CSS));
  check('every page ships the bar compact, so nothing flashes before nav.js measures (' + pages.length + ' pages)', pages.length >= 15 && loose.length === 0, loose.join(', '));

  /* u.html is served under /u/<name>: a relative path there resolves to /u/<file> and is answered with the page itself */
  const rel = [...read('u.html').matchAll(/(?:src|href)="([^"]+)"/g)].map((m) => m[1]).filter((v) => !/^(\/|#|https?:|mailto:|data:|javascript:)/.test(v));
  check('every script, stylesheet and link on u.html is absolute (the responsive layer was 404ing on every Send Wall)', rel.length === 0, rel.join(', '));

  /* ═══ every word visible ═══ */
  check('text drawn inside a graphic is sized with the graphic, and the level ring puts its number and "LEVEL" apart, the pair centred on the ring', /--gfx-ring: clamp\(148px, calc\(var\(--text-floor\) \* 7\), 188px\);/.test(CSS) && /\.pc-core \{ width: var\(--gfx-ring\); height: var\(--gfx-ring\);/.test(CSS) && /\.pc-lbl \{ font-size: var\(--gfx-ring-lbl\);/.test(CSS + read('responsive.css')) && read('gamify.js').includes('<text x="60" y="49.7" text-anchor="middle" class="pc-num">') && read('gamify.js').includes('<text x="61" y="80.7" text-anchor="middle" class="pc-lbl">LEVEL</text>'));
  check('  ...a bar with a label inside takes its height from the label, which sits in the flow and may wrap (XP, diamond, the About steps)', /\.gxp:has\(\.gxp-text\) \{ font-size: max\(var\(--text-floor\), 0\.75rem\); height: auto; min-height: max\(var\(--bar-h, 26px\), calc\(1\.3em \+ 6px\)\);/.test(CSS) && /\.gd-bar:has\(\.gd-text\) \{ height: auto;/.test(CSS) && /\.gs-progress > \.gs-progress-text \{ position: relative; inset: auto;/.test(CSS) && /\.gs-progress \{[^}]*min-height: max\(26px, calc\(1\.3em \+ 6px\)\);/.test(CSS));
  check('  ...nothing pushes a page past a phone\'s screen: the white paper\'s column is minmax(0, 1fr), an address in code may break, the Send Power figure scales', /grid-template-columns: minmax\(0, 1fr\);   \/\* 1fr alone would stretch/.test(read('whitepaper.html')) && /\.body-grid \{ display: grid; grid-template-columns: minmax\(0, 1fr\);/.test(read('whitepaper.html')) && /code, \.mono, \.addr \{ overflow-wrap: anywhere; \}/.test(CSS) && /\.pc-power \{[^}]*clamp\(1\.8rem, 8\.5vw, 2\.9rem\)/.test(CSS));
  const allCss = readdirSync(PUB).filter((f) => f.endsWith('.css')).map((f) => read(f)).join('\n');
  check('no grid column has a fixed minimum wider than a phone\'s container (160px and up are capped at 100%)', !/minmax\((1[6-9]\d|[2-9]\d\d)px, *1fr\)/.test(allCss));
  check('names, titles and one-line readings wrap instead of being cut with "…" (responsive.css, loaded last)', /═══ Every word visible ═══/.test(read('responsive.css')) && /\.gsec-d, \.trk-w-label\) \{\n  white-space: normal; overflow: visible; text-overflow: clip; overflow-wrap: anywhere;\n\}/.test(read('responsive.css')) && /html :is\(\.cmp-name, /.test(read('responsive.css')));

  /* ═══ notifications ═══ */
  const RESP = read('responsive.css');
  check('the count sits inside its red circle: a 20–22px circle, digits at 58% of it, one line — and responsive.css no longer forces it up to the page floor', /\.notif-badge \{[^}]*min-width: var\(--notif-badge\); height: var\(--notif-badge\);[^}]*font-size: var\(--nav-fs-badge\);[^}]*line-height: 1;[^}]*white-space: nowrap;/.test(CSS) && /\.notif-badge \{ font-size: var\(--nav-fs-badge\); \}/.test(RESP) && !/\.notif-badge \{ font-size: max\(var\(--text-floor\)/.test(RESP + CSS));
  check('the panel pops up on the LEFT side of the screen, pinned under the bar, sized in text units and capped to the screen, never taller than the screen', /\.notif-panel \{ position: fixed; top: calc\(var\(--nav-h, 60px\) \+ 8px\); left: 8px; right: auto; font-size: max\(var\(--text-floor\), 0\.95rem\); width: min\(26em, calc\(100vw - 16px\)\); max-height: calc\(100vh - var\(--nav-h, 60px\) - 24px\);/.test(CSS) && /@supports \(height: 100dvh\) \{ \.notif-panel \{ max-height: calc\(100dvh - var\(--nav-h, 60px\) - 24px\); \} \}/.test(CSS) && /@media \(max-width: 600px\) \{ \.notif-panel \{ left: 8px; right: 8px; width: auto; \} \}/.test(CSS) && !/\.notif-panel \{\n    left: 0; right: auto;/.test(CSS));
  const NOTIF = read('notifications.js');
  check('  ...no hover-away close (a far-away bell made it close the list on the way and turn the bell click into a reopen): the bell, an outside click, Esc or a link close it', !/mouseleave|hoverTimer/.test(NOTIF) && /document\.addEventListener\('click', e => \{ if \(open && !mount\.contains\(e\.target\)\) toggle\(false\); \}\);/.test(NOTIF) && /if \(!open \|\| \(e\.key !== 'Escape' && e\.key !== 'Esc'\)\) return;/.test(NOTIF));
  check('  ...opened from the keyboard, focus moves into the list (a magnifier following focus sees it), with a visible ring', /if \(open && e\.detail === 0\) \{ const p = document\.getElementById\('notif-panel'\); if \(p\) p\.focus\(\); \}/.test(NOTIF) && /id="notif-panel" tabindex="-1"/.test(NOTIF) && /\.notif-panel:focus-visible \{ outline: 3px solid var\(--focus\);/.test(CSS));
  check('  ...the bell is drawn in the page font (a button does not inherit it), and the count\'s digits are centred on their ink, not their line box', /\.notif-bell \{[^}]*font-family: inherit;[^}]*line-height: 1;/.test(CSS) && /\.notif-badge-n \{ display: block; text-box: trim-both cap alphabetic; \}/.test(CSS) && /<span class="notif-badge-n">/.test(NOTIF));
  check('  ...its text follows the page floor in em of the panel, so it grows with the screen and wraps rather than clips', /\.notif-text \{ font-size: max\(var\(--text-floor\), 1em\);[^}]*overflow-wrap: anywhere;/.test(CSS) && /\.notif-time \{ font-size: max\(var\(--text-floor\), 0\.8em\);/.test(CSS) && /\.notif-head \{[^}]*font-size: max\(var\(--text-floor\), 1em\);/.test(CSS));
  check('  ...its buttons are at least 36px, 44px under a finger', /\.notif-x \{[^}]*min-width: max\(36px, 1\.9em\); min-height: max\(36px, 1\.9em\);/.test(CSS) && /@media \(pointer: coarse\) \{ \.notif-x \{ min-width: max\(44px, 1\.9em\); min-height: max\(44px, 1\.9em\); \}/.test(CSS));
  check('  ...and while it is open the bar rises above Sendy, the compose button and the player, so no row is ever hidden under one', /\.nav:has\(#notif-panel\.open\) \{ z-index: 300; \}/.test(CSS));

  /* ═══ the OG strip ═══ */
  check('the OG banner is a strip: a button head with aria-expanded/aria-controls, and the rest hidden until tapped', /<button class="og-banner-head" id="og-banner-head" type="button" aria-expanded="false" aria-controls="og-banner-more" data-tip="/.test(INDEX) && /<div class="og-banner-more" id="og-banner-more" hidden>/.test(INDEX) && !/<a class="og-banner"/.test(INDEX));
  check('  ...the head carries the medal, the title, one line, the live countdown and a chevron', /<span class="og-banner-title">Become an <span class="og-word">OG<\/span>/.test(INDEX) && /<span class="og-banner-brief">/.test(INDEX) && /<span class="og-timer og-timer-head">/.test(INDEX) && /<span class="og-chev" aria-hidden="true">/.test(INDEX));
  check('  ...the rest keeps the full copy, both timers and the one honest action, now a real link', /<div class="og-banner-more"[\s\S]*<span class="og-banner-sub">[\s\S]*<span class="og-banner-timers">[\s\S]*<a class="og-banner-cta" id="og-banner-cta" href="about\.html#og-rules">/.test(INDEX) && (INDEX.match(/data-og-window="current"/g) || []).length === 2);
  check('home.js pops it down and remembers it for the visit; the CTA link (not the banner) takes the href', /head\.addEventListener\('click', \(\) => setOpen\(more\.hidden\)\)/.test(HOME) && /sessionStorage\.setItem\('og-open'/.test(HOME) && /cta\.setAttribute\('href', href\);/.test(HOME) && !/banner\.setAttribute\('href'/.test(HOME) && /labels\.forEach/.test(HOME));
  check('  ...the head stays one row at every width: the summary only where it fits, the clock without its label on a tablet, title and chevron on a phone', /@media \(max-width: 1699px\) \{ \.og-banner-brief \{ display: none; \} \}/.test(CSS) && /@media \(max-width: 899px\) \{ \.og-banner \.og-timer-head i \{ display: none; \}/.test(CSS) && /@media \(max-width: 560px\) \{ \.og-banner \.og-timer-head \{ display: none; \} \.og-banner \.og-banner-head \{ flex-wrap: nowrap; \}/.test(CSS) && /\.og-banner \.og-timer-head \{ flex-direction: row;/.test(CSS));
  check('  ...styled: the head is a full-width row at least 56px tall with a visible focus ring; the rest is hidden by [hidden]', /\.og-banner-head \{[^}]*min-height: 56px;[^}]*cursor: pointer;/.test(CSS) && /\.og-banner-head:focus-visible \{ outline: 3px solid #ffd27a;/.test(CSS) && /\.og-banner-more\[hidden\] \{ display: none; \}/.test(CSS) && /\.og-banner\.og-open \.og-chev \{ transform: rotate\(180deg\); \}/.test(CSS));
  check('  ...nothing in the strip says buy', !/\b(buy now|should buy)\b/i.test(INDEX.slice(INDEX.indexOf('<div class="og-banner"'), INDEX.indexOf('</div>', INDEX.indexOf('og-banner-more')))));
  /* ═══ the OG badge opens the About page's OG section ═══ */
  const APP = read('app.js'), ABOUT = read('about.html');
  check('every OG badge goes to the About page\'s OG section, and that section exists', /window\.OG_RULES_HREF = '\/about\.html#og-rules';/.test(APP) && /id="og-rules"/.test(ABOUT));
  check('  ...a badge on its own is a real link (keyboard and middle-click work); the composer opens it in a new tab so a draft stays put', /return '<a class="' \+ cls \+ '" href="' \+ window\.OG_RULES_HREF \+ '"' \+ \(where === 'new-tab' \? ' target="_blank" rel="noopener"'/.test(APP) && /ogBadge\(AUTH\.user\.og, 'new-tab'\)/.test(read('compose.js')));
  const inLink = [['auth.js', /trg\.className = 'profile-link'[\s\S]{0,400}ogBadge\(user\.og, 'in-link'\)/], ['sendcall.js', /<a class="sc-sender-who"[^\n]*ogBadge\(s\.og, 'in-link'\) : ''\) \+ '<\/a>'/], ['search.js', /a\.className = 'search-hit';[\s\S]{0,500}ogBadge\(u\.og, 'in-link'\)/]];
  check('  ...inside another link (nav name pill, a call\'s sender row, a search hit) it is a span, never a link in a link', inLink.every(([f, re]) => re.test(read(f))), inLink.filter(([f, re]) => !re.test(read(f))).map(([f]) => f).join(','));
  const plainCalls = readdirSync(PUB).filter((f) => f.endsWith('.js')).flatMap((f) => [...read(f).matchAll(/ogBadge\((?:[^()]|\([^()]*\))*\)/g)].map((m) => f + ': ' + m[0]));
  check('  ...and every other caller is outside a link (only the three above pass in-link)', plainCalls.filter((c) => /'in-link'/.test(c)).length === 3, plainCalls.filter((c) => /'in-link'/.test(c)).join(' | '));
  check('  ...one capture-phase click handler: a span badge cancels its outer link and goes to the OG section; a card behind it never fires', /document\.addEventListener\('click', function \(e\) \{\n    var b = [^\n]*closest\('\.og-badge'\)[\s\S]{0,160}e\.stopPropagation\(\);\n    if \(b\.tagName === 'A'\) return;\n    e\.preventDefault\(\);[\s\S]{0,160}location\.href = window\.OG_RULES_HREF;\n  \}, true\);/.test(APP));
  check('  ...it looks clickable: pointer cursor, no underline, a visible focus ring', /a\.og-badge, \.og-badge\[data-og-link\] \{ cursor: pointer; text-decoration: none; \}/.test(CSS) && /a\.og-badge:focus-visible \{ outline: 3px solid/.test(CSS));
  /* ═══ the OG $SEND site beside the $GWC card on the home page ═══ */
  const PAIR = INDEX.slice(INDEX.indexOf('<div class="origin-pair">'), INDEX.indexOf('<!-- ===== WALL TEASER'));
  const OGS = PAIR.slice(PAIR.indexOf('<div class="gwc-hero og-site'));
  check('the home page pairs the $GWC card with a JustSendItCoin.com card in the same style (the gwc-hero base, a green variant)', PAIR.indexOf('<h3>Powered by Generational Wealth Coin</h3>') > 0 && PAIR.indexOf('<div class="gwc-hero og-site reveal">') > PAIR.indexOf('Powered by Generational Wealth Coin'));
  check('  ...it says this is the OG site and links to JustSendItCoin.com in a new tab', /<p class="og-site-tag">🏅 The OG site<\/p>/.test(OGS) && /<a class="btn btn-primary" href="https:\/\/JustSendItCoin\.com" target="_blank" rel="noopener"/.test(OGS));
  check('  ...its description is the site\'s own: its tagline, and the 1% liquidity tax this site states too', OGS.includes('“You don’t hold it. You send it.”') && /1% tax that feeds the liquidity pool/.test(OGS) && /1% buy \/ sell \/ transfer tax → auto-adds to liquidity/.test(INDEX));
  check('  ...no buy language in the card', !/\bbuy\b|\bape\b|\bpurchase\b/i.test(OGS.replace(/<!--[\s\S]*?-->/g, '').replace(/<[^>]+>/g, ' ')));
  check('  ...side by side where two fit, stacked below 1100px, never a fixed-minimum column', /\.origin-pair \{ display: grid; grid-template-columns: repeat\(auto-fit, minmax\(min\(22rem, 100%\), 1fr\)\);/.test(CSS) && /@media \(max-width: 1099px\) \{ \.origin-pair \{ max-width: 620px; \} \}/.test(CSS));
  /* ═══ button labels centred in their buttons ═══ */
  const RESP2 = read('responsive.css');
  check('buttons draw their label in the page font (a <button> does not inherit it; the chart amounts and copy buttons were Arial) on a fixed line, so an emoji cannot push the words down', /button \{ line-height: 1\.2; font-family: inherit; \}/.test(CSS));
  check('  ...a letter-spaced .btn balances the tracking after its last letter with the same indent before its first (child elements reset it)', /html \.btn \{ text-indent: 0\.04em; \}\nhtml \.btn > \* \{ text-indent: 0; \}/.test(RESP2) && /\.btn \{[^}]*letter-spacing: 0\.04em/.test(CSS));
  check('  ...the "Send it" button: the label\'s trailing tracking cancelled and the ✏️ nudged onto the line\'s middle', /html #compose-fab \.fab-label \{ margin-right: -0\.03em; line-height: normal; \}/.test(RESP2) && /html #compose-fab \.fab-ico \{ padding-top: 0\.08em; \}/.test(RESP2) && /#compose-fab \{[^}]*letter-spacing: 0\.03em/.test(CSS));
  check('  ...and the display font\'s capitals sit on the middle of the line (patched ascent 1736 / descent 312 in the served files)', /luckiest-guy-latin-09b57828\.woff2/.test(read('fonts/fonts.css')) && /luckiest-guy-latin-ext-be6f3912\.woff2/.test(read('fonts/fonts.css')));
} catch (e) {
  console.error('ERROR', e.message, e.stack && e.stack.split('\n')[1]);
  check('the suite ran to the end', false, e.message);
}
let pass = 0;
for (const [n, ok, extra] of results) { console.log((ok ? 'PASS ' : 'FAIL ') + n + (extra ? '  [' + extra + ']' : '')); if (ok) pass++; }
console.log(`\n${pass}/${results.length} passed`);
